version: "3.4"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4
    ports:
      - "2181:2181"

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:${KAFKA_VERSION}
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: hostname -i
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092,SASL_PLAINTEXT://kafka1:9093,SASL_SSL://kafka1:9094,SSL://kafka1:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,SASL_PLAINTEXT://kafka1:9093,SASL_SSL://kafka1:9094,SSL://kafka1:9095
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SSL_KEYSTORE_LOCATION: "/kafka-client/.github/kafka/cert/kafka1/server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: phpkafka123456
      KAFKA_SSL_KEY_PASSWORD: phpkafka123456
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/kafka-client/.github/kafka/cert/server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: phpkafka123456
#      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka-client/.github/kafka/jaas.conf"
    command: "/kafka-client/.github/kafka/start_kafka.sh"
    volumes:
      - "${GITHUB_WORKSPACE}:/kafka-client:rw"
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
      - "9095:9095"

  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka:${KAFKA_VERSION}
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: hostname -i
      KAFKA_LISTENERS: PLAINTEXT://kafka2:19092,SASL_PLAINTEXT://kafka2:19093,SASL_SSL://kafka2:19094,SSL://kafka2:19095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:19092,SASL_PLAINTEXT://kafka2:19093,SASL_SSL://kafka2:19094,SSL://kafka2:19095
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SSL_KEYSTORE_LOCATION: "/kafka-client/.github/kafka/cert/kafka2/server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: phpkafka123456
      KAFKA_SSL_KEY_PASSWORD: phpkafka123456
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/kafka-client/.github/kafka/cert/server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: phpkafka123456
#      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka-client/.github/kafka/jaas.conf"
    command: "/kafka-client/.github/kafka/start_kafka.sh"
    volumes:
      - "${GITHUB_WORKSPACE}:/kafka-client:rw"
    ports:
      - "19092:19092"
      - "19093:19093"
      - "19094:19094"
      - "19095:19095"

  swoole:
    container_name: "swoole"
    build:
      context: .
      dockerfile: ./swoole.dockerfile
      args:
        SWOOLE_VERSION: ${SWOOLE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
    volumes:
      - "${GITHUB_WORKSPACE}:/kafka-client:rw"
    working_dir: /kafka-client
    ulimits:
      core: -1
    privileged: true
    command: tail -f /etc/group
