version: "3.4"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4
    ports:
      - "2181:2181"

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:${KAFKA_VERSION}
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HOST_NAME: kafka1
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: hostname -i
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092,SASL_PLAINTEXT://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,SASL_PLAINTEXT://kafka1:9093
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      #      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka-client/.github/kafka/jaas.conf"
    command: "/kafka-client/.github/kafka/start_kafka.sh"
    volumes:
      - "${GITHUB_WORKSPACE}:/kafka-client:rw"
    ports:
      - "9092:9092"
      - "9093:9093"

  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka:${KAFKA_VERSION}
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_HOST_NAME: kafka2
      KAFKA_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: hostname -i
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9094,SASL_PLAINTEXT://kafka1:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9094,SASL_PLAINTEXT://kafka1:9095
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      #      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka-client/.github/kafka/jaas.conf"
    command: "/kafka-client/.github/kafka/start_kafka.sh"
    volumes:
      - "${GITHUB_WORKSPACE}:/kafka-client:rw"
    ports:
      - "9094:9094"
      - "9095:9095"

  swoole:
    container_name: "swoole"
    build:
      context: .
      dockerfile: ./swoole.dockerfile
      args:
        SWOOLE_VERSION: ${SWOOLE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
    volumes:
      - "${GITHUB_WORKSPACE}:/kafka-client:rw"
    working_dir: /kafka-client
    ulimits:
      core: -1
    privileged: true
    command: tail -f /etc/group
