name: Static Code Analysis

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        swoole: [4.5-php7.1]
        kafka: [2.13-2.7.0]

    env:
      SWOOLE_VERSION: ${{ matrix.swoole }}
      KAFKA_VERSION: ${{ matrix.kafka }}

    steps:
      - uses: actions/checkout@v2

      - name: Start docker
        run: |
          cd .github
          # run
          docker-compose up -d
          # swoole
          docker exec swoole php -v && docker exec swoole php --ri swoole && docker exec swoole composer -V
          docker ps -a && docker ps

      - name: Prepare
        run: |
          docker exec swoole composer update

      - name: Test
        run: docker exec swoole ./vendor/bin/phpstan analyse --memory-limit 1G
